spring:
  application:
    name: ssm-55-persist
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/C:\devprograms\h2\ssm_55
    username: sa
    password:
    driver-class-name: org.h2.Driver
