logging:
  level:
    root: INFO
    org.springframework.statemachine: DEBUG
security:
  basic:
    enabled: false
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/C:\devprograms\h2\ssm_54
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
